version: '3'
services:
  check-token:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile
      environment:
        TZ: America/Sao_Paulo
        server.error.include-message: always
      ports:
        - '8080:8080'
      command: mvn spring-boot:run